FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG NODE_ENV
ARG MONGO_URI
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GITHUB_TOKEN
ARG GITHUB_REDIRECT_URI
ARG SESSION_SECRET

ENV NODE_ENV=${NODE_ENV}
ENV MONGO_URI=${MONGO_URI}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
ENV SESSION_SECRET=${SESSION_SECRET}

COPY . .

EXPOSE 5000

CMD ["node", "index.js"]