version: '3.8'
services:
  app:
    container_name: pyfiddle-backend
    build: .
    image: pyfiddle-backend
    ports:
      - "5000:5000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/pyfiddle
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: